/**
 * Reference candidate dossiers used to drive deterministic seeding of the
 * intelligence layer at boot. Real deployments stream real dossiers; these
 * exist so the framework is never empty on first paint and so the agents
 * can be exercised against worked examples.
 */

import type { CandidateDossier } from "./types.js";

export const SAMPLE_DOSSIERS: CandidateDossier[] = [
  {
    candidateId: "cand-001",
    name: "Avery Park",
    targetRole: "Staff Platform Engineer",
    organizationContext: {
      priorBaseline: 0.22,
      complexityFloor: 0.55,
      criticalDomains: ["distributed-systems", "leadership", "reliability"],
    },
    claims: [
      {
        id: "claim-001",
        domain: "distributed-systems",
        source: "cv",
        text: "Led distributed systems redesign serving 40M DAU.",
        selfStatedStrength: 0.9,
      },
      {
        id: "claim-002",
        domain: "leadership",
        source: "interview",
        text: "Mentored team of eight engineers across two timezones.",
        selfStatedStrength: 0.8,
      },
      {
        id: "claim-003",
        domain: "reliability",
        source: "cv",
        text: "Drove 99.99% availability for tier-1 surface.",
        selfStatedStrength: 0.85,
      },
    ],
    evidence: [
      {
        id: "ev-001",
        domain: "distributed-systems",
        source: "github",
        kind: "supports",
        weight: 0.85,
        summary: "Authored consensus-layer refactor merged across 3 services.",
        claimId: "claim-001",
      },
      {
        id: "ev-002",
        domain: "distributed-systems",
        source: "interview",
        kind: "supports",
        weight: 0.7,
        summary: "Explained quorum failure modes with first-principles reasoning.",
        claimId: "claim-001",
      },
      {
        id: "ev-003",
        domain: "leadership",
        source: "reference",
        kind: "supports",
        weight: 0.8,
        summary: "Reference: 'consistently elevated peers; ran weekly design reviews.'",
        claimId: "claim-002",
      },
      {
        id: "ev-004",
        domain: "reliability",
        source: "github",
        kind: "supports",
        weight: 0.65,
        summary: "Owned runbooks and SLO definitions in shared repo.",
        claimId: "claim-003",
      },
      {
        id: "ev-005",
        domain: "reliability",
        source: "interview",
        kind: "neutral",
        weight: 0.4,
        summary: "Could not recall last incident's RCA without prompting.",
      },
    ],
    roles: [
      {
        id: "role-a1",
        title: "Software Engineer",
        startedAt: "2017-08-01",
        endedAt: "2019-09-01",
        durationMonths: 25,
        complexity: 0.35,
        scope: 0.3,
        ownership: 0.2,
        teamSize: 5,
      },
      {
        id: "role-a2",
        title: "Senior Engineer",
        startedAt: "2019-09-01",
        endedAt: "2022-01-01",
        durationMonths: 28,
        complexity: 0.55,
        scope: 0.5,
        ownership: 0.45,
        teamSize: 6,
      },
      {
        id: "role-a3",
        title: "Tech Lead",
        startedAt: "2022-01-01",
        endedAt: "2024-06-01",
        durationMonths: 29,
        complexity: 0.78,
        scope: 0.72,
        ownership: 0.7,
        teamSize: 8,
      },
      {
        id: "role-a4",
        title: "Principal Engineer",
        startedAt: "2024-06-01",
        endedAt: null,
        durationMonths: 18,
        complexity: 0.86,
        scope: 0.82,
        ownership: 0.78,
        teamSize: 10,
      },
    ],
    github: {
      yearlyContributions: [
        { year: 2021, commits: 412, repos: 8 },
        { year: 2022, commits: 689, repos: 11 },
        { year: 2023, commits: 901, repos: 14 },
        { year: 2024, commits: 1120, repos: 17 },
      ],
      signatureProjects: [
        {
          name: "raft-extensions",
          year: 2023,
          complexity: 0.82,
          ownership: 0.75,
          domain: "distributed-systems",
        },
        {
          name: "slo-toolkit",
          year: 2024,
          complexity: 0.7,
          ownership: 0.9,
          domain: "reliability",
        },
      ],
    },
    interview: {
      depthByDomain: {
        "distributed-systems": 0.8,
        leadership: 0.7,
        reliability: 0.6,
      },
      reasoningQuality: 0.78,
      vocabularyWithoutDepth: 1,
    },
  },
  {
    candidateId: "cand-002",
    name: "Jordan Mehta",
    targetRole: "Staff Platform Engineer",
    organizationContext: {
      priorBaseline: 0.22,
      complexityFloor: 0.55,
      criticalDomains: ["distributed-systems", "leadership", "reliability"],
    },
    claims: [
      {
        id: "claim-101",
        domain: "distributed-systems",
        source: "cv",
        text: "Distributed systems expert with planet-scale experience.",
        selfStatedStrength: 0.95,
      },
      {
        id: "claim-102",
        domain: "leadership",
        source: "cv",
        text: "Led engineering org of 30+ engineers.",
        selfStatedStrength: 0.9,
      },
      {
        id: "claim-103",
        domain: "ml-infrastructure",
        source: "interview",
        text: "Hands-on ML infrastructure architect.",
        selfStatedStrength: 0.85,
      },
    ],
    evidence: [
      {
        id: "ev-101",
        domain: "distributed-systems",
        source: "interview",
        kind: "refutes",
        weight: 0.65,
        summary: "Could not articulate CAP trade-offs beyond surface definitions.",
        claimId: "claim-101",
      },
      {
        id: "ev-102",
        domain: "distributed-systems",
        source: "github",
        kind: "refutes",
        weight: 0.6,
        summary: "No public distributed-systems contributions in past 3 years.",
      },
      {
        id: "ev-103",
        domain: "leadership",
        source: "reference",
        kind: "refutes",
        weight: 0.7,
        summary: "Reference described role as 'individual contributor on a large team.'",
      },
      {
        id: "ev-104",
        domain: "ml-infrastructure",
        source: "github",
        kind: "neutral",
        weight: 0.3,
        summary: "Forked two ML training repos; no original commits.",
      },
      {
        id: "ev-105",
        domain: "reliability",
        source: "interview",
        kind: "supports",
        weight: 0.45,
        summary: "Described basic on-call rotation experience.",
      },
    ],
    roles: [
      {
        id: "role-b1",
        title: "Engineer",
        startedAt: "2016-05-01",
        endedAt: "2019-03-01",
        durationMonths: 34,
        complexity: 0.35,
        scope: 0.3,
        ownership: 0.25,
        teamSize: 12,
      },
      {
        id: "role-b2",
        title: "Senior Engineer",
        startedAt: "2019-03-01",
        endedAt: "2022-05-01",
        durationMonths: 38,
        complexity: 0.5,
        scope: 0.4,
        ownership: 0.3,
        teamSize: 20,
      },
      {
        id: "role-b3",
        title: "Senior Engineer",
        startedAt: "2022-05-01",
        endedAt: null,
        durationMonths: 42,
        complexity: 0.52,
        scope: 0.42,
        ownership: 0.32,
        teamSize: 30,
      },
    ],
    github: {
      yearlyContributions: [
        { year: 2021, commits: 180, repos: 4 },
        { year: 2022, commits: 165, repos: 4 },
        { year: 2023, commits: 142, repos: 3 },
        { year: 2024, commits: 110, repos: 3 },
      ],
      signatureProjects: [],
    },
    interview: {
      depthByDomain: {
        "distributed-systems": 0.35,
        leadership: 0.3,
        "ml-infrastructure": 0.25,
        reliability: 0.5,
      },
      reasoningQuality: 0.36,
      vocabularyWithoutDepth: 6,
    },
  },
  {
    candidateId: "cand-003",
    name: "Sam Reyes",
    targetRole: "Founding Engineer",
    organizationContext: {
      priorBaseline: 0.15,
      complexityFloor: 0.6,
      criticalDomains: [
        "product-engineering",
        "ownership",
        "distributed-systems",
      ],
    },
    claims: [
      {
        id: "claim-201",
        domain: "ownership",
        source: "cv",
        text: "Built and shipped 3 zero-to-one products end-to-end.",
        selfStatedStrength: 0.92,
      },
      {
        id: "claim-202",
        domain: "product-engineering",
        source: "interview",
        text: "Comfortable across product, infra, and design.",
        selfStatedStrength: 0.78,
      },
    ],
    evidence: [
      {
        id: "ev-201",
        domain: "ownership",
        source: "github",
        kind: "supports",
        weight: 0.9,
        summary: "Sole maintainer of two production OSS projects with >2k stars.",
        claimId: "claim-201",
      },
      {
        id: "ev-202",
        domain: "product-engineering",
        source: "github",
        kind: "supports",
        weight: 0.8,
        summary: "Shipped end-to-end SaaS as solo founder (frontend + infra + API).",
        claimId: "claim-202",
      },
      {
        id: "ev-203",
        domain: "distributed-systems",
        source: "github",
        kind: "supports",
        weight: 0.55,
        summary: "Designed sharded queue in one of the OSS projects.",
      },
      {
        id: "ev-204",
        domain: "product-engineering",
        source: "interview",
        kind: "supports",
        weight: 0.7,
        summary: "Walked through three product decisions with crisp trade-off framing.",
      },
    ],
    roles: [
      {
        id: "role-c1",
        title: "Engineer",
        startedAt: "2020-06-01",
        endedAt: "2021-08-01",
        durationMonths: 14,
        complexity: 0.4,
        scope: 0.35,
        ownership: 0.5,
        teamSize: 4,
      },
      {
        id: "role-c2",
        title: "Founding Engineer",
        startedAt: "2021-08-01",
        endedAt: "2023-09-01",
        durationMonths: 25,
        complexity: 0.7,
        scope: 0.75,
        ownership: 0.85,
        teamSize: 3,
      },
      {
        id: "role-c3",
        title: "Founder",
        startedAt: "2023-09-01",
        endedAt: null,
        durationMonths: 26,
        complexity: 0.82,
        scope: 0.88,
        ownership: 0.95,
        teamSize: 2,
      },
    ],
    github: {
      yearlyContributions: [
        { year: 2021, commits: 520, repos: 6 },
        { year: 2022, commits: 880, repos: 9 },
        { year: 2023, commits: 1340, repos: 12 },
        { year: 2024, commits: 1810, repos: 15 },
      ],
      signatureProjects: [
        {
          name: "kona-queue",
          year: 2023,
          complexity: 0.75,
          ownership: 0.95,
          domain: "distributed-systems",
        },
        {
          name: "studio-os",
          year: 2024,
          complexity: 0.82,
          ownership: 0.95,
          domain: "product-engineering",
        },
      ],
    },
    interview: {
      depthByDomain: {
        "product-engineering": 0.82,
        ownership: 0.9,
        "distributed-systems": 0.55,
      },
      reasoningQuality: 0.8,
      vocabularyWithoutDepth: 0,
    },
  },
];
